#!/usr/bin/sh
# #####################################################################################
#       __       _______   __        ______
#      /""\     /"     "| /""\      /    " \
#     /    \   (: ______)/    \    // ____  \   Copyright (c) 2020-2022 Andres Angarita
#    /' /\  \   \/    | /' /\  \  /  /    ) :)  https://github.com/angaritaoa
#   //  __'  \  // ___)//  __'  \(: (____/ //   Email: angaritaoa@gmail.com
#  /   /  \\  \(:  (  /   /  \\  \\        /
# (___/    \___)\__/ (___/    \___)\"_____/
#
# Mi configuración personalizada de bspwm
# #####################################################################################

# Si pgrep no encuentra el proceso, el proceso se ejecuta
pgrep -x picom     > /dev/null || picom &
pgrep -x nitrogen  > /dev/null || nitrogen --restore &
pgrep -x polybar   > /dev/null || polybar --reload statusbar &
pgrep -x sxhkd     > /dev/null || sxhkd &

# command: xrandr
bspc monitor -d 1 2 3 4

bspc config border_width   1px
bspc config window_gap     10px
bspc config top_padding    54px
bspc config bottom_padding 0px
bspc config left_padding   0px
bspc config right_padding  0px

bspc config split_ratio        1px
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config normal_border_color   "#3F444A"
bspc config active_border_color   "#3F444A"
#bspc config focused_border_color  "#50AFEF"
bspc config focused_border_color  "#3F444A"
bspc config presel_feedback_color "#50AFEF"

# command: xprop
bspc rule -a "*" state=floating
bspc rule -a Gimp state=floating
bspc rule -a Emacs state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Gpick state=floating
bspc rule -a Inkscape state=floating
bspc rule -a URxvt state=floating
