install :
	ln -fs /mnt/archivos/github/dotfiles/config/bash/bashrc ~/.bashrc
	ln -fs /mnt/archivos/github/dotfiles/config/git/gitconfig ~/.gitconfig
	[ -d ~/.config/terminator ] || mkdir -p ~/.config/terminator
	ln -fs /mnt/archivos/github/dotfiles/config/terminator/config ~/.config/terminator/config
	cp -fR /mnt/archivos/.ssh ~/
