#+title: NetworkManager-wait-online

Los scripts de  red heredados sincrónicos iteran a través  de todos los archivos
de   configuración  para   configurar  los   dispositivos.  Aplican   todas  las
configuraciones relacionadas  con la  red y se  aseguran de que  la red  esté en
línea.

El servicio =NetworkManager-wait-online=  espera con un tiempo de espera  a que se
configure la red.  Esta configuración de la red implica  conectar un dispositivo
Ethernet,   buscar   un   dispositivo    Wi-Fi,   etc.   NetworkManager   activa
automáticamente  los perfiles  adecuados que  están configurados  para iniciarse
automáticamente.  El fallo  del proceso  de  activación automática  debido a  un
tiempo de  espera de DHCP o  un evento similar podría  mantener a NetworkManager
ocupado durante  un largo  periodo de tiempo.  Dependiendo de  la configuración,
NetworkManager reintenta activar el mismo perfil o un perfil diferente.

Cuando la puesta  en marcha se completa,  todos los perfiles están  en estado de
desconexión o  se activan con éxito.  Puede configurar los perfiles  para que se
conecten automáticamente.

Ejecutar el siguiente comando para desactivar este servicio:

#+begin_src bash
$ sudo systemctl disable NetworkManager-wait-online.service
#+end_src
